### ISSUE TITLE
Error check in DB insert isn't working.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#28] opened 2015-06-24 07:19 UTC
(Note commit dffcf53 was latest when I filed this.)

In `routes/index.js`, this code should print a database connection failure error to the console log if, say, CouchDB isn't running:

    requestDb.insert(
        {
            name: name,
            street_address: street_address,
            city: city,
            state: state,
            zip: zip_5,
            phone: phone,
            may_text: may_text
        },
        'Request from ' + req.body.name + ' at ' +  new Date().toLocaleString(),
        function(err, body, header) {
            if (err) {
                console.log("ERROR: '" + err.message + "'");
                return;
            }
        });

But I ran the app with CouchDB turned off, and that error is never printed.  The later error, in the function passed to addressDB.view(), does print what I expected to the console log:

        if (error) {
            if (String(error).toLowerCase().indexOf("error happened in your connection") != -1) {
                console.log("ERROR: " + error)
                console.log("       (This probably means you forgot to start CouchDB.)\n")
            } else {
                console.log("DEBUG: unrecognized error: " + error);
            }
        }

So, we're somehow not detecting the error correctly in the first case.  (I presume there *is* an error on insert, since CouchDB was down!)  Maybe the prototype for `function(err, body, header)` is wrong or something?  Not sure yet.

**Comment by cecilia-donnelly** [comment] 2016-02-19 21:56
This is a duplicate of issue #3 and gives some more details that might be of interest.

**Closed by cecilia-donnelly** 2016-02-19 21:56 UTC
