### ISSUE TITLE
We are using "assignedRegion" but we probably don't need to -- "rc_region" codes are enough.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#113] opened 2015-08-26 23:46 UTC
Although `models/request.js` does not have an `assignedRegion` field for the Request model, we still seem to have that field in the code in various places.  I originally started investigating why it looked like Requests had both `rc_region` (as expected) *and* `assignedRegion` (I wasn't sure what that was for, or if it was redundant with `rc_region`).  Then when I looked at the model, `assignedRegion` was not there (whew) but was still present in various places in the code (hmm).  What's going on?

        models/index.js:db.Request.belongsTo(db.SelectedCounties, {foreignKey:'assignedRegion'});
        models/index.js:db.SelectedCounties.hasMany(db.Request, {foreignKey:'assignedRegion'});
        public/views/admin/requests/index.js:      assignedRegion: '',
        public/views/admin/requests/index.min.js:!function(){"use strict";app=app||{},app.Record=Backbone.Model.extend({idAttribute:"id",defaults:{id:void 0,name:"",address:"",address_2:"",city:"",state:"",zip:"",phone:"",email:"",assignedRegion:"",selectedCount
        public/views/admin/requests/index.min.js.map:{"version":3,"file":"index.min.js","sources":["index.js"],"names":["app","Record","Backbone","Model","extend","idAttribute","defaults","id","undefined","name","address","address_2","city","state","zip","phone"
        views/index.js:    request.assignedRegion = region.id;
        views/index.js:    return request.save({fields: ['assignedRegion']});

(Similarly to the situation in issue #112, not all of the result lines above show the string "assignedRegion", but that's only because the results are truncated here -- if the file+line is listed, it means there will be a match there when we go into the file itself.)

**Comment by kfogel** [comment] 2015-08-27 00:04
Ah, okay, these lines in `models/index.js` are probably a clue:

        db.Request.belongsTo(db.SelectedCounties, {foreignKey:'assignedRegion'});
        db.SelectedCounties.hasMany(db.Request, {foreignKey:'assignedRegion'});

**Comment by trystant** [comment] 2015-08-27 00:12
I'm not clear.

Is this an explicit dupe of #99?

**Comment by kfogel** [comment] 2015-08-27 00:28
Thanks for responding, @trystant.  I'm not sure how this would be a dup of #99?

I'm trying to understand what the `assignedRegion` field is for, given that Requests already have an `rc_region` field.  Having this understanding became somewhat more urgent today because I was trying to set up some static sample data for Requests (see https://github.com/redcross/smoke-alarm-portal/commit/8c61725cd442205373c3aa792d7d8034d611dfc4 on the `wip_requests_static_sample_data` branch), and I couldn't import my first attempt at sample data because of an fkey constraint failure on `assignedRegion` w.r.t. `SelectedCounties`.  Now, it could be that my dev box database is simply out-of-date and that I should refresh.  However, the general question remains: is `assignedRegion` still being used, or is it obsolete?  If it is obsolete, we should remove it from the code entirely.  If it is still being used, I'd like to understand what it is used for, because at first glance it seems redundant with the `rc_region` field we already have.  (If the relevant model files documented what the two fields were for, that would probably solve this, in the latter case.)

**Comment by trystant** [comment] 2015-08-27 00:48
Hi @kfogel. So in #99, the discussion of address_2 was changed to rc_region
in order to facilitate showing the display. The fact that both rc_region
and assignedRegion exist and is used. This was true two weeks ago
<https://github.com/redcross/smoke-alarm-portal/issues/99#issuecomment-130457270>.
It's still being used and one of those fields can be removed as an
enhancement.

The only other potential argument to keep assignedRegion is that it's an
integer which would be quicker to search if the number of requests gets
high, but that would be a performance optimization.

At this point, the assignedRegion is used to link to the SelectedCounties,
while the rc_region is solely used to display the region result in the
admin.

I hope this helps.



On Wed, Aug 26, 2015 at 8:28 PM, Karl Fogel <notifications@github.com>
wrote:

> Thanks for responding, @trystant <https://github.com/trystant>. I'm not
> sure how this would be a dup of #99
> <https://github.com/redcross/smoke-alarm-portal/issues/99>?
>
> I'm trying to understand what the assignedRegion field is for, given that
> Requests already have an rc_region field. Having this understanding
> became somewhat more urgent today because I was trying to set up some
> static sample data for Requests (see 8c61725
> <https://github.com/redcross/smoke-alarm-portal/commit/8c61725cd442205373c3aa792d7d8034d611dfc4>
> on the wip_requests_static_sample_data branch), and I couldn't import my
> first attempt at sample data because of an fkey constraint failure on
> assignedRegion w.r.t. SelectedCounties. Now, it could be that my dev box
> database is simply out-of-date and that I should refresh. However, the
> general question remains: is assignedRegion still being used, or is it
> obsolete? If it is obsolete, we should remove it from the code entirely. If
> it is still being used, I'd like to understand what it is used for, because
> at firs t glance it seems redundant with the rc_region field we already
> have. (If the relevant model files documented what the two fields were for,
> that would probably solve this, in the latter case.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redcross/smoke-alarm-portal/issues/113#issuecomment-135216638>
> .
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant

**Comment by kfogel** [comment] 2015-08-27 01:55
It helps, thanks so much!  (The string "assignedRegion" does not appear in issue #99, until the reference to this issue, so that's probably why my scan didn't clarify things for me).

I don't understand how `assignedRegion` is being used to link to SelectedCounties given that in `data/selected_counties.js`, we are clearly using `rc_region`-style codes.  In other words, both our Requests model and the SelectedCounties model natively use `rc_region` anyway, or at least the model for the former and the static source data for the latter do.  It seems to me there should be no need to introduce an `assignedRegion` numeric code into this mix -- we already have the mapping we want "for free".  It is kind of premature optimization to add in a numeric code when there is no evidence we would have a performance problem.

So we should have one code-wise representation of Red Cross regions, and it should be the `rc_region` code (that is, a text field), and it should be used in the Requests model, the SelectedCounties model, and (eventually I guess we'll want this) maybe a separate model that just maps between `rc_region` codes and display names like "Eastern Missouri", etc.

Does this make sense?

**Comment by cecilia-donnelly** [comment] 2015-09-02 17:42
So, after some investigation, it looks like we *are* using "assignedRegion" on prod.  Currently, the "Requests" table has both an "rc_region" column and an "assignedRegion" column.  No values are being stored in "rc_region."  Integer values are being stored in "assignedRegion," and they correspond to ids in "SelectedCounties."  The "region" column in that table matches the region codes we're using elsewhere, and which I expected to see in the "rc_region" column in the "Requests" table.

This means that "assignedRegion" is misnamed.  It is used as a foreign key to the region, but really the integer stored in that column corresponds to a *county*.

Properly, we should drop the "assignedRegion" column and fill the "rc_region" column with the region codes.

**Comment by cecilia-donnelly** [comment] 2015-09-08 21:19
As of d652714, "assignedRegion" only appears in two minified files (`public/views/admin/requests/index.min.js.map` and `public/views/admin/requests/index.min.js`), which are presumably not being used.  I'm not sure why we have them in the repository, even.

**Closed by cecilia-donnelly** 2015-09-08 21:19 UTC
Labels: question
