### ISSUE TITLE
New user needs to be created with manual process

### ISSUE THREAD

**Issue by trystant** [redcross/smoke-alarm-portal#49] opened 2015-07-09 20:04 UTC
The smoke-alarm-portal application is being retrofitted with a fork of the [drywall](https://github.com/trystant/drywall) application. The current app has a manual process for setting up a new user which can be optimized. This is a placeholder feature request to be addressed in future versions of the site.

**Comment by cecilia-donnelly** [comment] 2016-01-28 16:31
I think #138 is a duplicate of this one -- oops.  Closing this one, though, because #138 has more information about how we want this feature to work.

**Closed by cecilia-donnelly** 2016-01-28 16:31 UTC
Labels: enhancement
