### ISSUE TITLE
When the getasmokealarm URL is used in social media, have the appropriate Region appear (where the post is made)

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#249] opened 2018-04-11 03:32 UTC
"Hey Jim –

One of the Executive Directors in my region recently held a smoke alarm event in her local community (Hastings, NE) and utilized the getssmokealarm.org to register homes. When they posted the link on Facebook it was showing the Chicago, IL, Northern Illinois Region information (see below). Is there a way to get around your regions information being shared when we post the link?

Thanks,

Brandon J. Holstrom  |  Regional Disaster Officer"

![getamokealarm - nebraska facebook](https://user-images.githubusercontent.com/4147733/38595035-0f2facca-3d0f-11e8-969c-36283ba2a96a.jpg)

**Comment by cecilia-donnelly** [comment] 2018-04-11 14:48
See #118, which has some overlap with this issue.

**Comment by kfogel** [comment] 2018-04-18 19:35
Overlap, or maybe they're just the same issue?  Anyway, OTS is going to solve this.  I'll mention issue #118 here again so that issue gets an update about this comment.

**Comment by cecilia-donnelly** [comment] 2018-04-26 14:53
The body of this issue is a duplicate of #118, but the title mentions something different: "have the appropriate Region appear (where the post is made)."  The bug fix in #118 and in the request in the body of this issue is to remove the CHNI information from Facebook.  

A much bigger change would be to find the location of the person logged in to Facebook and show them the information of their Red Cross region.  If that's a desired feature we should track and estimate it as a separate issue.  It would not be a quick fix.

Closing this issue for now in favor of #118 -- we can open a new one for geolocation if that is something we want to work on down the line.

**Closed by cecilia-donnelly** 2018-04-26 14:53 UTC
Labels: high priority
